# Generated by Django 2.2.11 on 2021-01-26 07:06

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models

import ing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=60)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
            ],
            bases=(ing.models.JsonFieldMappedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin",
                    django_cryptography.fields.encrypt(models.CharField(max_length=8)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("transaction_date", models.DateTimeField()),
                ("extended_description", models.CharField(max_length=200)),
                ("receipt_number", models.CharField(max_length=10)),
                ("transaction_id", models.IntegerField(unique=True)),
                ("transaction_type", models.IntegerField()),
                ("transaction_group", models.CharField(max_length=20)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ing.Account"
                    ),
                ),
            ],
            bases=(ing.models.JsonFieldMappedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cif", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(max_length=30)),
                ("salutation", models.CharField(max_length=10)),
                (
                    "credentials",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ing.Credentials",
                    ),
                ),
            ],
            bases=(ing.models.JsonFieldMappedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ing.Client"
            ),
        ),
    ]
